-- AprovaQuest V1 — schema + políticas + dados iniciais
create extension if not exists pgcrypto;

create table if not exists public.usuarios (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.assuntos (
  id bigint generated by default as identity primary key,
  materia text not null,
  nome text not null,
  slug text not null,
  descricao text not null default '',
  created_at timestamptz not null default now(),
  unique (materia, slug)
);

create table if not exists public.questoes (
  id bigint generated by default as identity primary key,
  materia text not null,
  assunto text not null,
  dificuldade text not null check (dificuldade in ('Fácil','Médio','Difícil')),
  titulo text not null,
  slug text not null unique,
  enunciado text not null,
  alternativa_a text not null,
  alternativa_b text not null,
  alternativa_c text not null,
  alternativa_d text not null,
  alternativa_e text not null,
  resposta_correta text not null check (resposta_correta in ('A','B','C','D','E')),
  explicacao text not null,
  dica text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists questoes_materia_idx on public.questoes(materia);
create index if not exists questoes_assunto_idx on public.questoes(assunto);
create index if not exists questoes_dificuldade_idx on public.questoes(dificuldade);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists questoes_set_updated_at on public.questoes;
create trigger questoes_set_updated_at before update on public.questoes
for each row execute function public.set_updated_at();

alter table public.questoes enable row level security;
alter table public.assuntos enable row level security;
alter table public.usuarios enable row level security;

drop policy if exists "public read questoes" on public.questoes;
create policy "public read questoes" on public.questoes for select using (true);

drop policy if exists "public read assuntos" on public.assuntos;
create policy "public read assuntos" on public.assuntos for select using (true);

drop policy if exists "admins insert questoes" on public.questoes;
create policy "admins insert questoes" on public.questoes for insert to authenticated
with check (exists (select 1 from public.usuarios u where u.id=auth.uid() and u.is_admin=true));

drop policy if exists "admins update questoes" on public.questoes;
create policy "admins update questoes" on public.questoes for update to authenticated
using (exists (select 1 from public.usuarios u where u.id=auth.uid() and u.is_admin=true))
with check (exists (select 1 from public.usuarios u where u.id=auth.uid() and u.is_admin=true));

drop policy if exists "admins delete questoes" on public.questoes;
create policy "admins delete questoes" on public.questoes for delete to authenticated
using (exists (select 1 from public.usuarios u where u.id=auth.uid() and u.is_admin=true));

-- O público não precisa ler a tabela usuarios.
drop policy if exists "users read own profile" on public.usuarios;
create policy "users read own profile" on public.usuarios for select to authenticated
using (id=auth.uid());

-- Inserção de assuntos iniciais.
insert into public.assuntos (materia,nome,slug,descricao) values ('Biologia','Citologia','citologia','Assuntos e questões de Citologia para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Biologia','Ecologia','ecologia','Assuntos e questões de Ecologia para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Biologia','Fotossíntese','fotossintese','Assuntos e questões de Fotossíntese para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Biologia','Genética','genetica','Assuntos e questões de Genética para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Biologia','Sistema imunológico','sistema-imunologico','Assuntos e questões de Sistema imunológico para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Física','Cinemática','cinematica','Assuntos e questões de Cinemática para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Física','Eletricidade','eletricidade','Assuntos e questões de Eletricidade para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Física','Energia cinética','energia-cinetica','Assuntos e questões de Energia cinética para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Física','Trabalho e energia','trabalho-e-energia','Assuntos e questões de Trabalho e energia para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Matemática','Função afim','funcao-afim','Assuntos e questões de Função afim para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Matemática','Função quadrática','funcao-quadratica','Assuntos e questões de Função quadrática para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Matemática','Juros compostos','juros-compostos','Assuntos e questões de Juros compostos para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Matemática','Juros simples','juros-simples','Assuntos e questões de Juros simples para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Matemática','Porcentagem','porcentagem','Assuntos e questões de Porcentagem para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Química','Concentração','concentracao','Assuntos e questões de Concentração para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Química','Estequiometria','estequiometria','Assuntos e questões de Estequiometria para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Química','Ligações químicas','ligacoes-quimicas','Assuntos e questões de Ligações químicas para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Química','Separação de misturas','separacao-de-misturas','Assuntos e questões de Separação de misturas para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;
insert into public.assuntos (materia,nome,slug,descricao) values ('Química','pH','ph','Assuntos e questões de pH para estudo no AprovaQuest.') on conflict (materia,slug) do nothing;

-- Questões originais da V1.
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Matemática','Porcentagem','Fácil','Desconto em uma camiseta','desconto-camiseta','Uma camiseta custa R$ 80,00. Em uma promoção, a loja oferece 25% de desconto sobre o preço original. Qual é o preço da camiseta após o desconto?','R$ 55,00','R$ 60,00','R$ 62,00','R$ 65,00','R$ 70,00','B','25% de R$ 80,00 é 0,25 × 80 = R$ 20,00. Subtraindo o desconto do preço original: 80 − 20 = R$ 60,00.','Calcule primeiro o valor correspondente aos 25% e depois subtraia do preço original.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Matemática','Função afim','Médio','Corrida de aplicativo','corrida-aplicativo','Uma empresa de transporte cobra uma taxa fixa de R$ 6,00 mais R$ 2,50 por quilômetro percorrido. Qual expressão representa o preço P, em reais, de uma corrida de x quilômetros?','P(x)=6x+2,50','P(x)=2,50x−6','P(x)=2,50x+6','P(x)=8,50x','P(x)=6x−2,50','C','A taxa fixa é o termo constante 6. O valor que varia com a distância é 2,50 por quilômetro, então P(x)=2,50x+6.','Em uma função afim, identifique o custo fixo e o custo que cresce proporcionalmente à variável.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Matemática','Função quadrática','Médio','Área de um canteiro','area-canteiro-funcao-quadratica','A largura de um canteiro retangular mede x metros e seu comprimento mede x+3 metros. Se a área é 28 m², qual é o valor positivo de x?','3','4','5','6','7','B','A área é x(x+3)=28, portanto x²+3x−28=0. Fatorando, (x+7)(x−4)=0. As soluções são −7 e 4; como medida deve ser positiva, x=4.','Monte a equação da área e procure as raízes da equação quadrática.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Matemática','Juros simples','Fácil','Aplicação com juros simples','aplicacao-juros-simples','Uma estudante aplica R$ 1.200,00 a juros simples de 2% ao mês durante 5 meses. Qual será o valor dos juros obtidos?','R$ 100,00','R$ 110,00','R$ 120,00','R$ 130,00','R$ 140,00','C','Nos juros simples, J=C·i·t. Assim, J=1200×0,02×5=R$ 120,00.','Use J = capital × taxa × tempo, mantendo a taxa na forma decimal.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Matemática','Juros compostos','Médio','Crescimento de uma poupança','crescimento-poupanca-juros-compostos','Um valor de R$ 1.000,00 é aplicado a juros compostos de 10% ao mês durante 2 meses. Qual será o montante ao final do período?','R$ 1.100,00','R$ 1.120,00','R$ 1.200,00','R$ 1.210,00','R$ 1.220,00','D','O montante é M=C(1+i)^t. Logo, M=1000(1,10)^2=1000×1,21=R$ 1.210,00.','Em juros compostos, a taxa incide também sobre os juros acumulados do período anterior.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Física','Cinemática','Fácil','Velocidade média de uma viagem','velocidade-media-viagem','Um ciclista percorre 18 km em 1,5 hora, mantendo uma velocidade média constante. Qual é sua velocidade média em km/h?','9','10','12','15','18','C','A velocidade média é dada por v=Δs/Δt. Portanto, v=18/1,5=12 km/h.','Divida a distância total pelo tempo total gasto no percurso.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Física','Cinemática','Médio','Aceleração de um carrinho','aceleracao-carrinho','Um carrinho aumenta sua velocidade de 4 m/s para 16 m/s em 6 segundos, com aceleração constante. Qual é sua aceleração média nesse intervalo?','1 m/s²','2 m/s²','3 m/s²','4 m/s²','6 m/s²','B','A aceleração é a variação da velocidade dividida pelo intervalo de tempo: a=(16−4)/6=12/6=2 m/s².','Use a = (velocidade final − velocidade inicial) / tempo.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Física','Trabalho e energia','Médio','Trabalho de uma força horizontal','trabalho-forca-horizontal','Uma força horizontal constante de 30 N desloca uma caixa por 5 m na mesma direção da força. Qual é o trabalho realizado pela força?','6 J','25 J','35 J','150 J','300 J','D','Quando força e deslocamento têm a mesma direção, W=F·d. Assim, W=30×5=150 J.','Se a força estiver na mesma direção do deslocamento, o cosseno do ângulo é 1.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Física','Energia cinética','Fácil','Energia cinética de uma bola','energia-cinetica-bola','Uma bola de massa 2 kg se move com velocidade de 3 m/s. Qual é sua energia cinética?','3 J','6 J','9 J','12 J','18 J','C','A energia cinética é Ec=(m·v²)/2. Então Ec=(2×9)/2=9 J.','Eleve a velocidade ao quadrado antes de multiplicar pela massa e dividir por 2.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Física','Eletricidade','Médio','Corrente em um resistor','corrente-resistor','Um resistor de 10 Ω é ligado a uma fonte de 20 V. Considerando o resistor ideal, qual corrente elétrica passa por ele?','0,5 A','1 A','2 A','10 A','200 A','C','Pela Lei de Ohm, V=R·i. Logo, i=V/R=20/10=2 A.','Isole a corrente na Lei de Ohm: i=V/R.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Química','Estequiometria','Médio','Formação de água','estequiometria-formacao-agua','Na reação 2 H₂ + O₂ → 2 H₂O, quantos mols de água são formados quando 3 mols de O₂ reagem completamente, com H₂ em excesso?','2 mol','3 mol','4 mol','6 mol','9 mol','D','A equação mostra que 1 mol de O₂ produz 2 mols de H₂O. Portanto, 3 mols de O₂ produzem 6 mols de H₂O.','Use a proporção entre os coeficientes estequiométricos de O₂ e H₂O.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Química','pH','Fácil','Classificação de uma solução','classificacao-solucao-ph','Uma solução aquosa apresenta pH igual a 3 a 25 °C. Como essa solução é classificada?','Neutra','Básica','Ácida','Saturada','Metálica','C','Em condições usuais, pH menor que 7 indica uma solução ácida; pH igual a 7 é neutro e maior que 7 é básico.','Compare o pH informado com o valor 7.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Química','Concentração','Médio','Concentração comum de uma solução','concentracao-comum-solucao','Uma solução contém 20 g de soluto em 500 mL de solução. Qual é sua concentração comum em g/L?','10 g/L','20 g/L','40 g/L','50 g/L','100 g/L','C','500 mL correspondem a 0,5 L. A concentração comum é C=m/V=20/0,5=40 g/L.','Converta o volume para litros antes de aplicar C=m/V.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Química','Separação de misturas','Fácil','Separando areia e água','separacao-areia-agua','Uma mistura contém areia e água. Qual método é mais adequado para separar esses dois componentes?','Destilação fracionada','Filtração','Cromatografia','Sublimação','Fusão fracionada','B','A areia é um sólido insolúvel em água. Na filtração, o filtro retém o sólido e permite a passagem do líquido.','Pense em um método que retenha partículas sólidas insolúveis enquanto o líquido atravessa o filtro.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Química','Ligações químicas','Médio','Formação do cloreto de sódio','ligacao-quimica-cloreto-sodio','No cloreto de sódio (NaCl), formado por sódio e cloro, qual tipo de ligação predomina entre os íons?','Covalente apolar','Covalente polar','Metálica','Iônica','Ligação de hidrogênio','D','O sódio tende a perder um elétron e o cloro a ganhar um, formando íons de cargas opostas. A atração eletrostática entre eles caracteriza a ligação iônica.','Observe que há formação de íons por transferência de elétrons.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Biologia','Genética','Médio','Cruzamento entre heterozigotos','cruzamento-heterozigotos','Considere um gene com alelos A e a, em que A é dominante. Em um cruzamento Aa × Aa, qual é a probabilidade de um descendente apresentar o genótipo aa?','0%','25%','50%','75%','100%','B','Cada progenitor pode fornecer A ou a. As combinações possíveis são AA, Aa, Aa e aa. Uma das quatro é aa, portanto 25%.','Monte um quadro de Punnett ou liste as quatro combinações possíveis.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Biologia','Ecologia','Fácil','Fluxo de energia no ecossistema','fluxo-energia-ecossistema','Em uma cadeia alimentar, qual grupo geralmente ocupa o primeiro nível trófico e produz matéria orgânica a partir de energia luminosa?','Consumidores secundários','Decompositores','Produtores','Consumidores terciários','Parasitas','C','Os produtores, como plantas e algas, realizam fotossíntese e introduzem energia química na cadeia alimentar, formando o primeiro nível trófico.','Procure o grupo que produz seu próprio alimento usando energia externa, como a luz.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Biologia','Fotossíntese','Médio','Função da fotossíntese','funcao-fotossintese','Qual é uma consequência direta da fotossíntese realizada por plantas, algas e alguns microrganismos?','Consumo de oxigênio e produção de glicose','Produção de glicose e liberação de oxigênio','Produção de gás carbônico e consumo de glicose','Transformação de glicose em ácido lático','Produção exclusiva de proteínas','B','Na fotossíntese, energia luminosa é usada para produzir moléculas orgânicas, como glicose, a partir de CO₂ e água, com liberação de O₂.','Lembre-se dos principais reagentes e produtos da fotossíntese.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Biologia','Citologia','Fácil','Organelas e produção de energia','mitocondria-energia-celular','Qual organela está diretamente associada à maior parte da produção de ATP durante a respiração celular aeróbica em células eucarióticas?','Ribossomo','Lisossomo','Mitocôndria','Complexo golgiense','Centríolo','C','A mitocôndria abriga etapas centrais da respiração celular aeróbica e participa da produção de grande parte do ATP utilizado pela célula.','Associe a organela ao processo de respiração celular.') on conflict (slug) do nothing;
insert into public.questoes (materia,assunto,dificuldade,titulo,slug,enunciado,alternativa_a,alternativa_b,alternativa_c,alternativa_d,alternativa_e,resposta_correta,explicacao,dica) values ('Biologia','Sistema imunológico','Médio','Resposta imune e anticorpos','anticorpos-resposta-imune','Qual é uma função dos anticorpos produzidos pelo sistema imunológico adaptativo?','Transportar oxigênio','Reconhecer e se ligar a antígenos específicos','Produzir glicose','Realizar fotossíntese','Formar hemoglobina','B','Anticorpos são proteínas produzidas por células do sistema imune e podem reconhecer moléculas específicas, chamadas antígenos, contribuindo para sua neutralização ou eliminação.','Pense na especificidade: anticorpos reconhecem alvos moleculares específicos.') on conflict (slug) do nothing;

-- Para criar o primeiro administrador:
-- 1) Crie um usuário em Authentication > Users no painel do Supabase.
-- 2) Copie o UUID desse usuário.
-- 3) Execute:
-- insert into public.usuarios (id,nome,email,is_admin)
-- values ('UUID-DO-USUARIO','Administrador','seu-email@exemplo.com',true)
-- on conflict (id) do update set is_admin=true, email=excluded.email, nome=excluded.nome;
